### ISSUE TITLE
Quick fix list entries lead to new files

### ISSUE THREAD

**Issue by Squareys** [Squareys/vim-cmake#2]
How to reproduce:

1. Start (g)vim
2. Open a CMakeLists.txt with a project with some compile error
3. `:CMake`
4. `:make all | vert copen`
5. Select the error

Will lead to a new file rather than opening the path. This only seems to be an issue if the quick fix entry is a relative path.

**Workaround**: `:cd` to the build/ directory of the current CMake project (or just `cd` when highlighting the build directory in NERDTree).

Needs some further investigation.

**Comment by richteraj** [comment]
The generated output of a quickfix list command (like `:make`) will be parsed according
to the `errorformat` option.  This generates information on errors (file name, line number, etc.) and allows following to the according file.

The parsing tries to keep track of directory changes (`%D` and `%X` in `errorformat`) but CMake doesn't indicate directory changes and uses relative paths for generated build files.

A sample project tree to illustrate:

```
project/
  build/
    CMakeFiles/
    Makefile
    src/
  src/
  CMakeLists.txt
```
and a sample error for `:CMake`
```
CMake Error at CMakeLists.txt:109:
  ...

-- Configuring incomplete, errors occurred!
See also "/project/build/CMakeFiles/CMakeOutput.log".
Makefile:552: recipe for target 'cmake_check_build_system' failed
```

Only the line with `Makefile:` is recognized as an error, but the current directory doesn't have such a file.  Trying to open this file (i.e. as `/project/Makefile`) will edit a new file.

As a workaround we let `errorformat` recognize the CMake errors which appear first, e.g. `let &efm .= ',CMake %trror at %f:%l:'` (see pull request).  This will open `/project/CMakeLists.txt` at line 109 and not the non-existent file `/project/Makefile`.
Although the link to the Makefile will still not work.

**Comment by Squareys** [comment]
Hi @richteraj !

Thanks for having a go at this issue! I believe your pullrequest improves the error parsing definitely.
But regarding this issue, those now recognized CMakeLists.txt errors would still be relative to the current working directory, right? 

Hence, if I am at `project/build/` (because that is the directory that makes `Makefile` and other compiler error be opened correctly), it would try to open `project/build/CMakeLists.txt`?

I will see if I can fix this issue and will likely merge your pullrequest along the way.

Thanks again,
Cheers, Jonathan.

**Comment by Squareys** [comment]
I found that the issue here is only when using `-GNinja`, as the errors produced always contain file paths relative to the ninja makefiles.

**Comment by richteraj** [comment]
Hi Jonathan!

Thanks for the reply & remarks.

Yes You are right! I always started `:make` from `project/`. If I am for instance in `project/src` both links will lead to a new file…
To use quickfix for configuration issues one would have to start from `project/` (i.e. the parent of the build dir) as the working directory, so a solution would be a wrapper function for `:make`, which changes in the right dir first.

If I use Ninja as a generator the bug doesn't occur, for me the culprit is Unix Makefile. Maybe some plugin sets `errorformat` differently or the output generated by the underlying build system differs (version, OS, ...).

In conclusion my presented fix may break more then it fixes.

I changed things in my fork ([see diffs](/Squareys/vim-cmake/compare/master...richteraj:fix)) to a version suitable for my environment with some compromises:
- `g:cmake_config_in_quickfix` will turn on the `errorformat` and changes
- `:CMake` now uses internal CMake commands, which allows for quickfix errors for the CMake configuration and subsequent editing of `CMakeLists.txt`
    - config errors will be present in the quickfix list
- the `:make`-Wrapper `:CMakeCDMake`
- `:make` directly after `:Cmake` (from any working directory and with errors in `CMakeLists.txt`) works exactly once while getting the right error links
    - subsequent calls don't work (probably something to do with `CMakeCache.txt`)
    - either execute `:CMake` first or call `:CMakeCDMake`
- in effect while fixing errors in `CMakeLists.txt` files always use `:CMake`
- links into `project/build/` still don't work without breaking the source file links

Maybe there are some ideas which will lead to a general fix.

Best regards

**Comment by Squareys** [comment]
Hi @richteraj !

Sorry for the very late reply. I saw you added that last commit which fixes the tests to #3.
As far as I understand, this now does not break previous behaviour (unless explicitly configured with `g:cmake_config_in_quickfix`), so I am happy to merge that. I will have another look at the pullrequest in the next two days.

Cheers, Jonathan.

**Comment by richteraj** [comment]
Hi @Squareys,

No problem, I, too, didn't notice that I broke the build.  The `cmake_config_in_quickfix` variable is actually not directly related and is an additional feature to catch CMake build errors inside the quickfix list at the setup time (`:CMake`).  I accidentally merged this into the fix branch and thereby broke the build.

To circumvent the empty Makefile opening You have to call `:make` either from the project top level directory or use `CMakeCDMake` which does this for You.

Should I clean up the branch, so that the `g:cmake_config_in_quickfix` feature is not pulled together with this?

Best regards

**Comment by richteraj** [comment]
Hi @Squareys!

Actually, the `g:cmake_config_in_quickfix` is also related to that behavior...  and it has to be set in `.vimrc`.

I added some tests to test the new behavior.

I also added the test to confirm that the old behavior doesn't change, if there are no CMake specific errors (i.e. running your tests with `g:cmake_config_in_quickfix` enabled).
Unfortunately, this does not pass with Travis CI but passes with AppVeyor.  I suspect it is because Travis uses Vim 7.4 which behaves differently than Vim 8 for the test cases that call `make` (case 4 and 5).  I tried recreating the error locally (using Vim 7.4) but failed (i.e. the test passed).  So I disabled this test script for now.
Do You have some input on what could be wrong?

Best regards

**Comment by Squareys** [comment]
Hi @richteraj !

I finally found some time to have a look at this. First of all, thank you very much for your effort. This looks very clean to me and I will try to get this merged as soon as possible.
As for travis hanging, I fear that may be related to cmake being a little older there: [3.2.2](https://travis-ci.org/Squareys/vim-cmake/builds/280053143#L589)

~~So maybe [this line](https://github.com/Squareys/vim-cmake/pull/3/files#diff-1df6d83a738d618d58db7fdc674800fdR126) has something to do with it...~~ \* Will investigate further, though.
I made some changes, which I could try to push to your branch. You may need to "allow edits from maintainers" on the pullrequest, though, maybe. Never pushed to someone elses pullrequest before 😅 

Will tell you once I figured this out :)

\* *Edit: cmake -H -B  actually works with 3.2.2*

**Comment by richteraj** [comment]
Hi @Squareys!

Thanks for your answer!  Don't worry about pushing your changes back to me, I'll pull it myself (I, too, have no idea how you could push to my repo 😉)

Best regards

**Comment by Squareys** [comment]
@richteraj I managed :D Seems like I'm allowed to push to that branch you created the PR for 👍 

You'll need to pull, of course.

**Comment by richteraj** [comment]
Hi @Squareys!

I agree with removing the second `.vimrc`, but we have to use `--cmd` to set `c:cmake_config_in_quickfix` before loading the plugin (because `errorformat`is set globally only once).  I also moved the cmake_quickfix.vader test before the failing one.

Best regards

**Comment by Squareys** [comment]
Fixed for `:CMake` config errors thanks to @richteraj in #3 and the rest within the process of merging #3.
